/// WHY CONST AND FINAL
/// IF YOU NEVER WANT TO CHANGE A VALUE THEN USE FINAL AND CONST KEYWORDS...
///
/// DIFFERENCE BETWEEN FINAL AND CONST
///
/// FINAL VARIABLE CAN ONLY BE SET ONCE AND IT IS INTIALIZED WHEN ACCESSED.
///
/// CONST VARIABLE IS IMPLICITLY FINAL BUT IT IS A COMPILE TIME CONSTANT
///     ie. IT IS INITIALIZED DURING COMPILIATION
///
/// INSTANCE VARIALBE CAN BE FINAL BUT CANNOT BE CONST
/// IF YOU WANT A CONSTANT AT CLASS LEVEL THEN MAKE IT STATIC CONST
///
///
///

void main() {
  // final keyword
  final cityName = "delhi";

  // const keyword
  const Country = 'india';
}

class Circle {
  final color = "Red";
  static const PI = 3.14;
}
