/// INTROUCTION TO FUNCTIONS?
/// SYNTAX AND PROPERITES OF A FUNCTION
/// FUNCTION AS EXPRESSIONS
/// DIFFERNT TYPE OF FUNCTION PARAMETERS
/// *REQURIRED PARAMETERS
/// *OPTIONAL PARAMETERS
/// functions are objects....
///
