// ? WHAT DOES INSTANCE VARIABLE OR INSTANCE FIELD OR INSTANCE PROPERTY
// * THE ANSWER IS THE SAME VARIABLE OR THE SAME FIELD OR INSTANCE PROPERTY IS CALLED WITH INSTANCE WITH NO CHANGES IN THE CODE......

// ? WHAT DOES IMMUTABLITY MEAH?
// * THE IMMUTABLE MEANS UNCHANGABLE

// ? WHAT DOES MUTABLE MEAN?
// * THE MUTABLE MEAN IT IS CHANGEABLE......

// ? WHAT IS THE DIFFERENCE BETWEEN CONST AND FINAL?

// * THE CONST KEYWORD CANNOT SET TO A VALUE THAT IS SET AFTER THE CODE IS COMPLIED

// * THE FINAL KEYWORD THE OLD ONE GET DESTORY AND NEW ONE GETS CREATED THAT TO IN THE SAME PROPERTY....

// EG:
void main() {
  // you can' set this to a const the time gets changed every minute const myconst DateTime.now();
  // but in the case of final you can do it
  final myfinal = DateTime.now();

  print(myfinal);
}
